### ISSUE TITLE
Is there a way to require documentation for all functions/classes?

### ISSUE THREAD

**Issue by micthiesen** [microsoft/tsdoc#228] opened 2020-04-23 20:29 UTC
Apologies if this is documented somewhere, but if it was I couldn't find it.

I'm looking for a way to enforce that at least some level of documentation is provided for every function (or interface, React component, etc.) in my team's project. Thank you.

**Comment by octogonz** [comment] 2020-04-23 23:12
Duplicate of https://github.com/microsoft/tsdoc/issues/209

As noted mentioned in that issue, we would like to build this feature into the `eslint-plugin-tsdoc` ruleset for ESLint.  We need someone to propose a design.  The actual implementation is probably pretty easy.

**Closed by octogonz** 2020-04-23 23:12 UTC
