### ISSUE TITLE
VS Code says "unable to load schema" because it redirects to `en-US`

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/tsdoc#253] opened 2020-08-17 13:32 UTC
VS Code throws an JSON Schema error because `https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json` is redirecting to `https://developer.microsoft.com/en-us/json-schemas/tsdoc/v0/tsdoc.schema.json`. When changing the `$schema` to the redirected URL I get schema validation again but eslint now prints:

```
Error loading TSDoc config file:
Errors encountered for ./tsdoc.json:
  Unsupported JSON "$schema" value; expecting "https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json"
eslinttsdoc/syntax
```

**Comment by octogonz** [comment] 2020-08-18 04:22
@muuvmuuv  Thanks for reporting this!  Something might be wrong with the schema server. I'll ask around.

**Comment by octogonz** [comment] 2020-08-18 04:53
Interestingly, this problem does NOT apply to other schema URLs from the same server.  For example, this one does not redirect:

https://developer.microsoft.com/json-schemas/rush/rush.schema.json

And if you add `en-us`, it redirects back to the above URL:

https://developer.microsoft.com/en-us/json-schemas/rush/rush.schema.json

It seems that each folder must be individually configured, since the ones that work are older projects, and the ones that are broken are newer projects.  We need to find the person who administers that web server, and get them to generalize the configuration to apply to all folders.

**Comment by josh-biddick** [comment] 2021-09-09 22:33
@octogonz Has anyone followed up the administrator to resolve this issue. Heft config schemas are unable to load as well. .e.g `Unable to load schema from 'https://developer.microsoft.com/json-schemas/heft/typescript.schema.json': Request vscode/content failed unexpectedly without providing any details.`. I have to add the `en-us` portion to have them loaded correctly.

**Comment by octogonz** [comment] 2021-09-10 02:14
@apostolisms investigated earlier this summer but was unable to find anybody who owns that server.  (This problem affects other groups like SPFx and Teams, so I'm surprised someone else hasn't pursued it.)

My proposal was to relocate all the Rush Stack schemas to `https://rushstack.io/json-schemas/` which we control.  It's not ideal, but it's easy to implement.  If nobody has objections to that plan, lemme know.

**Comment by adamsemma** [comment] 2023-01-04 19:57
Problems loading reference 'https://json.schemastore.org/package': Unable to load schema from 'https://json.schemastore.org/package': getaddrinfo EAI_AGAIN json.schemastore.org.

**Comment by LGW22** [comment] 2023-02-27 16:03
someone know this problem? 

Problems loading reference 'vscode://schemas/settings/configurationDefaults': Unable to load schema from 'vscode://schemas/settings/configurationDefaults': cannot open vscode://schemas/settings/configurationDefaults. Detail: Unable to resolve text model content for resource vscode://schemas/settings/configurationDefaults.

**Comment by octogonz** [comment] 2023-02-28 03:51
> someone know this problem?
> 
> Problems loading reference 'vscode://schemas/settings/configurationDefaults': Unable to load schema from 'vscode://schemas/settings/configurationDefaults': cannot open vscode://schemas/settings/configurationDefaults. Detail: Unable to resolve text model content for resource vscode://schemas/settings/configurationDefaults.

This problem sounds unrelated to this issue.

**Comment by octogonz** [comment] 2023-02-28 04:05
@DevArvindsa @iclanton @apostolisms  FYI I just confirmed that the redirect is still happening for https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json

**Comment by qionghe9** [comment] 2023-03-08 06:56
> 



> someone know this problem?
> 
> Problems loading reference 'vscode://schemas/settings/configurationDefaults': Unable to load schema from 'vscode://schemas/settings/configurationDefaults': cannot open vscode://schemas/settings/configurationDefaults. Detail: Unable to resolve text model content for resource vscode://schemas/settings/configurationDefaults.

I have encountered the same problem, how did you solve it?

**Comment by joshxyzhimself** [comment] 2023-03-27 09:33
Weird. I closed the tab of the file causing this error, the warning disappeared. I re-opened the tab of the file, warning did not reappear.

**Comment by JohnSmall** [comment] 2023-04-11 06:57
Strange, this problem started happening sometime in the last few weeks. When creating a devcontainer for Rails + Posgres then the container can't access the outside world because it only has the localhost network interface setup. And I get this error from the devcontainer file `Unable to load schema from 'https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json': getaddrinfo EAI_AGAIN raw.githubusercontent.com.`

But starting a Node + Postgres devcontainer has no problem at all because it creates an extra network interface which does allow contact with the outside world.

**Comment by brokenthorn** [comment] 2023-05-01 14:29
I have the same error. Autocomplete/suggestions don't work, which is how I noticed something was wrong:
![image](https://user-images.githubusercontent.com/2119004/235467548-2cac3f13-1e0f-46fa-a2c0-9407f1371299.png)

Error text:

```
Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.(768)
```

**Comment by MrZhuA00** [comment] 2023-05-04 09:56
> I have the same error. Autocomplete/suggestions don't work, which is how I noticed something was wrong: ![image](https://user-images.githubusercontent.com/2119004/235467548-2cac3f13-1e0f-46fa-a2c0-9407f1371299.png)
> 
> Error text:
> 
> ```
> Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.(768)
> ```

Hi, I also encountered the same problem,I've added following string to user settings, and the error was gone:
```
 "json.validate.enable": false
```

**Comment by blakeNaccarato** [comment] 2023-05-05 16:58
I can confirm that setting `"json.validate.enable": false` allows hover hints and completion to function again, e.g. in `settings.json` modification. However, this workaround throws out all JSON linting and reporting in the "Problems" pane, so it's sort of the nuclear option. This issue just cropped up for me in the past few days, so it may be a regression associated with the latest release?

After further investigation, I find that autocomplete/hover is restored _until next VSCode restart_ by (seemingly?) any modification of the `json.<...>` settings tree. But then, a `json` key modification must be made again every restart (even a trivial one) to "shake" VSCode into completing `settings.json` again. Here's a rundown:

1. Ensure all `json.<...>` tree of settings keys are initially at their defaults, e.g. none of these keys are explicitly specified in any of your `settings.json` (maybe unnecessary, but this is my starting state).
3. Restart VSCode (e.g. with `Developer: Reload Window`). Navigate to your user `settings.json`. The following warning presents in the Problems pane:

```Plaintext
Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.
```

4. Make a trivial setting modification in the `json` tree of settings keys, _even if that modification is a no-op, like explicitly specifying a default as its default value_. For example, put `"json.schemaDownload.enable": true,` at the top of your `settings.json` and save the file. This could've also been `"json.validate.enable": true` (I think, maybe?).
5. Check whether autocomplete/hover works properly in `settings.json`, completing settings names and such. It should work now.
6. You can even remove the edit you made in step (4), save `settings.json` again, and autocomplete/hover still works.
7. Restart VSCode.
8. Now autocomplete/hover is broken again in `settings.json`, until some modification to the `json.<...>` tree of settings is made again, like in step 4. For example, commenting out `"json.validate.enable": true` if it's there, and saving.

So this issue may have to do with unstable startup behavior of JSON schema handling, perhaps isolated to VSCode's own `settings.json` or perhaps all JSON schemas more broadly, and this unstable state can be temporarily fixed by poking a `json.<...>` settings key, but the unstable behavior returns on the next program start. At least in my case.

**Comment by SabitaOjha** [comment] 2023-05-10 12:14
Getting the following error while opening angular project in vs code. 
![error](https://github.com/microsoft/tsdoc/assets/110093135/b1c8a16f-c47d-4b3f-82ff-613201abd1c8)

**Comment by ypkkhatri** [comment] 2023-05-13 19:36
> Getting the following error while opening angular project in vs code. ![error](https://user-images.githubusercontent.com/110093135/237386899-b1c8a16f-c47d-4b3f-82ff-613201abd1c8.PNG)

I'm getting the same error from a few days back.

**Comment by Ender-Wang** [comment] 2023-05-20 09:33
**Error**: Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.(768)
**Fix**: add this line in the beginning of your `User/settings.json` file: `"json.schemaDownload.enable": true,`.

**Comment by Ender-Wang** [comment] 2023-05-25 14:45
> @Ender-Wang Thanks, that worked for me!
> Can you give more context? What does this configuration change do, and why is it necessary?

It seems the schema vscode trying to get is either not in the dir or the version doesn't matter what vscode expect. And the line enables vscode to download the desired version.

**Comment by Asiinoob** [comment] 2023-05-29 06:35
> Weird. I closed the tab of the file causing this error, the warning disappeared. I re-opened the tab of the file, warning did not reappear.

Same here.

**Comment by KnifeFed** [comment] 2023-06-14 21:07
> **Fix**: add this line in the beginning of your `User/settings.json` file: `"json.schemaDownload.enable": true,`.

That only works for me until VSCode is restarted.

**Comment by octogonz** [comment] 2023-06-14 22:56
I'm closing this issue because the original problem (redirecting to `en-us` localized URLs) has been solved. If anyone is still having trouble, please open a new GitHub issue with repro steps. Thanks!

**Closed by octogonz** 2023-06-14 22:56 UTC

**Comment by jayant0146** [comment] 2023-07-16 05:49
Kindly help me with this problem?

Problems loading reference 'vscode://schemas/settings/configurationDefaults': Unable to load schema from 'vscode://schemas/settings/configurationDefaults': cannot open vscode://schemas/settings/configurationDefaults. Detail: Unable to resolve text model content for resource vscode://schemas/settings/configurationDefaults.

**Comment by cebasfu93** [comment] 2023-07-19 13:08
I just encountered the same issue. Switching to the pre-release version of the Python extension solved it for me... for now 😅

**Comment by badasswp** [comment] 2026-01-04 04:07
> > I have the same error. Autocomplete/suggestions don't work, which is how I noticed something was wrong: ![image](https://user-images.githubusercontent.com/2119004/235467548-2cac3f13-1e0f-46fa-a2c0-9407f1371299.png)
> > Error text:
> > ```
> > Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.(768)
> > ```
> 
> Hi, I also encountered the same problem,I've added following string to user settings, and the error was gone:
> 
> ```
>  "json.validate.enable": false
> ```

This only masks any validation issues you might have in JSON file which I don't think is ideal. IMO this should be the right fix:

```json
"json.schemaDownload.enable": true,
```
